spring:
  application:
    name: mesa-ayuda-api
  profiles:
    active: dev   # primero levantamos con H2

# ── DEV (H2 en memoria) ─────────────────────────────────────────────
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:mesa;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
